version: '3'

services:
    sciencebeam-utils-py2:
        build:
            context: .
            args:
                base_image: python:2.7.14-stretch
                version: ${VERSION}
        image: elifesciences/sciencebeam-utils-py2:${IMAGE_TAG}
        networks: []
    sciencebeam-utils-py3:
        build:
            context: .
            args:
                base_image: python:3.6.8-stretch
                version: ${VERSION}
        image: elifesciences/sciencebeam-utils-py3:${IMAGE_TAG}

networks: {}
